### ISSUE TITLE
Per-Subscription Callbacks

### ISSUE THREAD

**Issue by tmbull** [hivemq/hivemq-mqtt-client-dotnet#106]
## 🚀 Feature Request

The feature I am requesting is essentially the `callback` feature in the HiveMQ Java Client. See [example](https://hivemq.github.io/hivemq-mqtt-client/docs/quick-start/#subscribing-to-a-topic) and [Javadoc](https://javadoc.io/static/com.hivemq/hivemq-mqtt-client/1.3.3/com/hivemq/client/mqtt/mqtt5/Mqtt5AsyncClient.html#subscribe-com.hivemq.client.mqtt.mqtt5.message.subscribe.Mqtt5Subscribe-java.util.function.Consumer-).

## 🔈 Motivation

I am currently evaluating migrating some .NET Core apps from the M2MQTT library to this one after having successfully migrating a number of Java applications from the Paho Java library to the HiveMQ Java library. You are all probably aware of my motivations for using this library (MQTT5 support, async APIs, etc.)

The motivations for adding this feature are primarily:
* Feature parity with the HiveMQ Java library (this makes it easy for users/orgs leveraging both libraries)
* Separation of concerns in client code
  * Ex. I might have two classes that subscribe to different MQTT topics for entirely different reasons. Methods/callbacks in these classes should not need to filter out irrelevant messages.

## 🛰 Alternatives

My current alternative is to implement this logic in my client application. I create a wrapper around the `IHiveMQClient` library that manages subscriptions internally and calls the relevant callbacks as needed.

## 📎 Additional context

Please let me know if any additional content is needed or if this feature already exists and I somehow missed it.

**Comment by pglombardo** [comment]
Hi Tristan - this is a great feature request/needs to be added.  Unfortunately I don't have an ETA yet - there are a couple other things I need to get out of the way first.  I'll keep this issue open and update here once I have some news/progress.

> My current alternative is to implement this logic in my client application. I create a wrapper around the IHiveMQClient library that manages subscriptions internally and calls the relevant callbacks as needed.

This is a fair work-around but I agree that it's not ideal.

**Comment by tmbull** [comment]
Thanks for the quick reply @pglombardo! I will continue to monitor for progress.

**Comment by pglombardo** [comment]
Hi @tmbull - Happy new year.  I'm putting this together now.  I'll should have a new release soon.

**Comment by pglombardo** [comment]
Per subscriptions have been added in [package v0.10.0](https://www.nuget.org/packages/HiveMQtt/).  I've also added a [bunch of documentation](https://hivemq.github.io/hivemq-mqtt-client-dotnet/docs/subscribing#per-subscription-callbacks) to hopefully help out.

If you give this a try, let me know how it goes @tmbull!

**Comment by pglombardo** [comment]
Since I haven't heard back I'll close this out.  If you still have any issues/questions, please let me know!
