### ISSUE TITLE
Payload format indicator contains always "UNSPECIFIED" value after publishing

### ISSUE THREAD

**Issue by dalbarracin** [hivemq/hivemq-mqtt-client-dotnet#108]
Hello guys :)

Here some reports regarding bugs found so far when publishing messages using c# client library.

## 🐛 Bug Report

A published message with `PayloadFormatIndicator = UTF8Encoded` is always sent with `Unspecified`. When a `Validate()` method is called, it is always being set to `Unspecified` when contains both values. This is wrong, it should only throw an exception if it contains a different value, `Unspecified` if it is nullalble or keep the current value. 

## 🔬 How To Reproduce

1. Define a client of type `HiveMQClient` with a specific options for your configuration.
2. Create a event handler for `client.OnPublishSent` event and assign to it. The event handler should print a value from `OnPublishSentEventArgs.PublishPacket.Message.PayloadFormatIndicator`.
3. Create an instance of `MQTT5PublishMessage` and set a value as `PayloadFormatIndicator = MQTT5PayloadFormatIndicator.UTF8Encoded`.
4. Finally publish the message defined in step 3 as `await client.PublishAync(message).ConfigureAwait(false)`

### Code Example

The code in discussion can be found [here](https://github.com/hivemq/hivemq-mqtt-client-dotnet/blob/9d708069e33ac0bbd762543314875e44a4527a12/Source/HiveMQtt/MQTT5/Types/MQTT5PublishMessage.cs#L176)

### Environment

The client is ran in `Windows 10 OS` with `dotnet 6 sdk` and `HiveMQTT v0.5.0` C# nuget package.

## 📈 Expected behavior

The value of the `PayloadFormatIndicator` should be the one it is set before publishing.

**Comment by pglombardo** [comment]
Doh! Great find @dalbarracin - I'll fix that up soon.  Thanks for reporting!

**Comment by pglombardo** [comment]
The fix for this has been added in [release 0.6.0](https://github.com/hivemq/hivemq-mqtt-client-dotnet/releases/tag/v0.6.0) which is building now and should be on NuGet soon.  Thanks for pointing this out @dalbarracin!

**Comment by dalbarracin** [comment]
Thank you @pglombardo for taking your time on this. NIcely done :)
