### ISSUE TITLE
Client is disconnected with KeepAliveTimeout if it only subscribes at QoS=0

### ISSUE THREAD

**Issue by eKremerAixtron** [hivemq/hivemq-mqtt-client-dotnet#182]
## 🐛 Bug Report

If a client has only subscriptions of QoS=0 and in these topics there is regular traffic, the client does not keep the session with ping requests alive. Hence, it gets terminated by the broker due to a KeepAliveTimeout.

From the mqtt documentation the client is expected to keep the session alive with a ping request, if no MQTT Control Packet is received by the server: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901045

For QoS the client does not send any control packets, however, the client does not trigger any ping requests. Further investigating, we found in our logging: 
2024-06-28 11:10:42.4243|DEBUG|HiveMQtt.Client.HiveMQClient|aixact_2-(CM)- Connected: last communications 00:00:00.0056341 ago
This suggests, the lastCommunicationTimer holds the wrong value in https://github.com/hivemq/hivemq-mqtt-client-dotnet/blob/5d66deb5e74b7a0d1b7315246c32f66401babbb0/Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs#L76

We expect the timer to be restarted only when sending control packages, but it is restarted on more occasions. See: 
https://github.com/hivemq/hivemq-mqtt-client-dotnet/blob/5d66deb5e74b7a0d1b7315246c32f66401babbb0/Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs#L952
and https://github.com/hivemq/hivemq-mqtt-client-dotnet/blob/5d66deb5e74b7a0d1b7315246c32f66401babbb0/Source/HiveMQtt/Client/HiveMQClientTrafficProcessor.cs#L934

## 🔬 How To Reproduce

1. Create and connect a client which only subscribes to topics at Quality of service 0 and keepalive not 0. 
2. Make sure there are publications on subscribed topics so there occur no breaks longer than keepalive/2
3. Wait for the broker to send a KeepAliveTimeout

### Environment

Where are you running/using this client?
dotnet 7.0 in a powershell core

What version of this client are you using?
0.20.0

Operating System?
Windows 11

Hardware or Device?

## 📈 Expected behavior

For keepalive not equal to 0 and QoS=0, I expect the client to send ping requests when not sending MQTT Control Packets ;)

**Comment by pglombardo** [comment]
Hi @eKremerAixtron - great find!  I'll put out a fix for this very soon.

**Comment by pglombardo** [comment]
Fix for this released in [v0.21.0](https://github.com/hivemq/hivemq-mqtt-client-dotnet/releases/tag/v0.21.0).  If you have any problems still, let me know.  Thanks for reporting!

**Comment by eKremerAixtron** [comment]
Thank you for your quick fix! We'll let you know if we still have issues.
