### ISSUE TITLE
Dns.GetHostEntryAsync may produce an error such as "(0x00002AF9): No such host known"

### ISSUE THREAD

**Issue by xuzimianxzm** [hivemq/hivemq-mqtt-client-dotnet#186]
## 🔬 How To Reproduce

This problem may not be easy to reproduce. It is related to the underlying system. I use a custom compiled Linux system. It may be because it does not have a DNS service. Although I set the MQTT server connection address to an IPv4 IP address, it still throws an exception in this line of code in the HiveMQClientSocket.cs file:
 `
IPHostEntry ipHostEntry = await Dns.GetHostEntryAsync(this.Options.Host).ConfigureAwait(false);
`

![image](https://github.com/user-attachments/assets/e5da7bc1-4435-4b8b-a753-f2649ccc5787)

### Code sample

System.Net.Sockets.SocketException (0x00002AF9): No such host known。
   at System.Net.Dns.GetHostEntryOrAddressesCore(IPAddress address, Boolean justAddresses, AddressFamily addressFamily, Nullable`1 startingTimestamp)
   at System.Net.Dns.GetHostEntryCore(IPAddress address, AddressFamily addressFamily, Nullable`1 startingTimestamp)
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_1(Object s, Int64 startingTimestamp)
   at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---

### Environment

Customer Linux

**Comment by pglombardo** [comment]
Hi @xuzimianxzm - what value did you provide for `Host` in `HiveMQClientOptions`?

**Comment by xuzimianxzm** [comment]
> Hi @xuzimianxzm - what value did you provide for `Host` in `HiveMQClientOptions`?

Thank you very much for replying to my question so quickly. The HiveMQClientOptions I provided are as follows:
`  var options = new HiveMQClientOptionsBuilder()
            .WithBroker("192.168.0.4")
            .WithPort(DefaultPort)
            .WithClientId($"xxx-{DateTime.Now.Ticks}")
            .WithAutomaticReconnect(true)
            .Build();
`

**Comment by pglombardo** [comment]
Thanks @xuzimianxzm.  I'm traveling but once I'm back I'll see if I can test this out and potentially find a work around soon.

**Comment by xuzimianxzm** [comment]
> Thanks @xuzimianxzm. I'm traveling but once I'm back I'll see if I can test this out and potentially find a work around soon.

That's awesome, thank you again, your work and your writing means so much to me.

**Comment by pglombardo** [comment]
Hi @xuzimianxzm - this should be fixed now via #187.  I'll release a new package with this fix very soon.

**Comment by pglombardo** [comment]
Hi @xuzimianxzm - the fix for this is released in [v0.22.1](https://github.com/hivemq/hivemq-mqtt-client-dotnet/releases/tag/v0.22.1).  Could you try out that package and let me know if it fixes the issue for you?

**Comment by xuzimianxzm** [comment]
> HiveMQClientSocket

Hi @pglombardo 
After testing, this issue has been fixed. Thank you so much, your response speed is amazing.
