### ISSUE TITLE
Certain (long?) MQTT packets are malformed

### ISSUE THREAD

**Issue by jordanwade90** [hivemq/hivemq-mqtt-client-dotnet#71]
Attempting to publish (or perhaps receive) MQTT packets with certain combinations of topic and payload produces malformed MQTT packets. I can’t nail down exactly what conditions make it happen, but it seems to depend at least on the lengths of those strings. The test case below triggers the bug:

```c#
var clientOptions = new HiveMQClientOptions
{
    // <redacted>
};
using var client = new HiveMQClient(clientOptions);
client.OnMessageReceived += (_, args) =>
{
    Console.WriteLine("Received {0} ({1} byte payload)", 
        args.PublishMessage.Topic, 
        args.PublishMessage.Payload?.Length ?? 0);
};

await client.ConnectAsync();
await client.SubscribeAsync("#");

var testMessage = new MQTT5PublishMessage
{
    Topic = "example12345678901234567891234567890123456",
    QoS = QualityOfService.AtLeastOnceDelivery,
    Payload = new byte[76],
};
await client.PublishAsync(testMessage);
await Task.Delay(1000);
```

which results in OnMessageReceived printing garbage for the “topic” string with a 0-byte payload.

I can make this happen every time if the topic string is exactly 42 bytes and the payload is at least 76; I assume other conditions can also trigger it, but I haven’t discovered them.

**Comment by jordanwade90** [comment]
Forgot to mention, this is with 0.1.10

**Comment by pglombardo** [comment]
Hi @jordanwade90 - this is great info thanks!  I know for sure there is an issue with  QoS 2 messages as pointed out in #68 but I'll test soon with your example above.  There's definitely something amiss somewhere.  I'll post back here once I have something.

**Comment by andygikling** [comment]
Bump.  This is a show stopper issue!

**Comment by pglombardo** [comment]
Fix in progress in #75.  It should be released tomorrow sometime.

**Comment by jordanwade90** [comment]
Looks fixed.

**Comment by pglombardo** [comment]
Same comment here as in #73 - thanks Jordan!
