### ISSUE TITLE
MQTT publish packets ≥ 128 bytes are malformed

### ISSUE THREAD

**Issue by jordanwade90** [hivemq/hivemq-mqtt-client-dotnet#73]
## 🐛 Bug Report

MQTT publish packets whose lengths are ≥ 128 bytes are malformed by [PublishPacket.cs:271](https://github.com/hivemq/hivemq-mqtt-client-dotnet/blob/v0.1.10/Source/HiveMQtt/MQTT5/Packets/PublishPacket.cs#L271) since the code assumes the varint only requires one byte. This may be related to #71 but is not the same thing, since that test case doesn't involve a packet this large.

## 🔬 How To Reproduce

Attempt to send a packet with a sufficiently large payload.

### Code sample

```c#
var clientOptions = new HiveMQClientOptions
{
    // <redacted>
};
using var client = new HiveMQClient(clientOptions);
await client.ConnectAsync();

var testMessage = new MQTT5PublishMessage
{
    Topic = "example",
    QoS = QualityOfService.AtLeastOnceDelivery,
    Payload = new byte[256],
};
await client.PublishAsync(testMessage);
```

### Environment

v0.1.10, Windows, .NET 6.0

## 📎 Additional context

Discovered while single-stepping in the debugger while troubleshooting #71.

**Comment by andygikling** [comment]
Also bump.  This also needs a solution asap.

**Comment by pglombardo** [comment]
Hi @andygikling - thanks for pointing this out.  I'll take a look on Monday for sure and post back here soon.

**Comment by pglombardo** [comment]
Hi @andygikling - Just an update - I found the issue. Writing the fixed header was overwriting some bytes in the variable header causing a malformed packet. Working on a fix now.

**Comment by pglombardo** [comment]
Fix in progress in #75.  It should be released tomorrow sometime.

**Comment by pglombardo** [comment]
[v0.2.0 has been released](https://github.com/hivemq/hivemq-mqtt-client-dotnet/releases/tag/v0.2.0) and is building now.  It should be live shortly.

Could you try out that release?  It should resolve the issue.

**Comment by jordanwade90** [comment]
Looks like 0.2.0 fixed this.

**Comment by pglombardo** [comment]
Excellent that is great to hear.  I'll close out this issue but if anything remains, feel free to create a new issue.  Thanks for the help in diagnosing this.
