### ISSUE TITLE
How do you connect with self made credentials to the broker?

### ISSUE THREAD

**Issue by hebrahimiacsis** [hivemq/hivemq-mqtt-client-dotnet#78]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/hivemq/hivemq-mqtt-client-dotnet/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/hivemq/hivemq-mqtt-client-dotnet/discussions).

## ❓ Question
I'm trying to connect to a broker in the cloud, specifically the azure event grid. I was able to connect using MQTTX as a test client, but needed to use specific certifications and keys in order to connect. I'm not authorized to connect using basic settings, how would I pass these credentials on to become authorized, particularly in .net

**Comment by pglombardo** [comment]
Hi @hebrahimiacsis!  Apologies for the late reply.  Since the client is in Beta, it doesn't have support for client certificates (yet).  We'll be adding this soon.  I'll update this issue once the feature is in and released.

**Comment by tmbull** [comment]
I just wanted to add that this feature is important to me as well. I did not notice initially that the client does not support client certs, and this is a blocker for my team to be able to use the client to connect to our existing broker.

@pglombardo, I noticed that pretty much all of the commits in this project are your own. I was wondering if you would accept outside contributions?

**Comment by pglombardo** [comment]
Understood - client certificate support is definitely needed sooner than later.

> @pglombardo, I noticed that pretty much all of the commits in this project are your own. I was wondering if you would accept outside contributions?

Absolutely - contributions are greatly appreciated.  The one requirement is that HiveMQ requires a signed contributor's license agreement.  I'll add the CLA bot to this repository this week.

**Comment by pglombardo** [comment]
Hi all - just an updated that [version 0.8.0 was just released](https://github.com/hivemq/hivemq-mqtt-client-dotnet/releases/tag/v0.8.0) with X.509 client certificate support.

This release should allow you to add one or more client certificates to the client for broker validation.

Documentation on custom client certificates is [here](https://hivemq.github.io/hivemq-mqtt-client-dotnet/docs/how-to/client-certificates).

If you have any problems - let me know.  Thanks for the patience and pointing this out!

**Comment by pglombardo** [comment]
Hi all - since this FR has been added I'll close out this issue.  If you have any issues using client certificates, let me know.  I'd be happy to help out.
