### ISSUE TITLE
Last Will and Testament

### ISSUE THREAD

**Issue by SommerPh** [hivemq/hivemq-mqtt-client-dotnet#83]
## 🚀 Feature Request

Does this client support [Last Will and Testament](https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/)?
I couldn't find any options for this.

**Comment by pglombardo** [comment]
Hi @SommerPh - LWT is planned for the next release which will be hopefully soon.  Once that is out, we'll update the documentation to reflect that as well.  I'll update here again once it's out.

**Comment by pglombardo** [comment]
Hi @SommerPh - Last will and testament support was just released in [version 0.3.0](https://github.com/hivemq/hivemq-mqtt-client-dotnet/releases/tag/v0.3.0) of the library.

https://www.nuget.org/packages/HiveMQtt/0.3.0

I'll close out this issue but if you have any troubles, please let us know by filing a new issue.  Thanks for your patience!
