### ISSUE TITLE
Client gets disconnected from broker - best way to reconnect

### ISSUE THREAD

**Issue by Spike433** [hivemq/hivemq-mqtt-client-dotnet#88]
## Checklist

Hello!

Friendly reminder, [`discussions`](https://github.com/hivemq/hivemq-mqtt-client-dotnet/discussions) is missing.

- [x] I've searched the project's [`issues`](https://github.com/hivemq/hivemq-mqtt-client-dotnet/issues?q=is%3Aissue).

## ❓ Question

My hivemq client gets disconnected after approximately 50mins. what is best way to reconnect.

```cs
 var options = new HiveMQClientOptions()
            {
                Host = broker.hivemq.com,
                Port = 1883,
                UseTLS = true,
                UserName = "admin",
                Password = "adminPassword",
                CleanStart = false,

                KeepAlive = 43200,
                SessionExpiryInterval = 2000,
            };
```

What do you recommend, 

1. Try to modify `HiveMQClientOptions` above to extend session, set `SessionExpiryInterval ` to `0` and add some reconnect method? 
2. add some reconnect option (not sure if it available)?

```java
Java (https://www.hivemq.com/article/hivemq-mqtt-client-features/reconnect-handling/)
 .automaticReconnectWithDefaultConfig()
```
4. manually disconnect and then connect after some period of time?

```cs
... 
_hiveMQTTClient.BeforeDisconnect += _hiveMQTTClient_BeforeDisconnect; 
private void _hiveMQTTClient_BeforeDisconnect(object sender, HiveMQtt.Client.Events.BeforeDisconnectEventArgs e)

    {
        Console.WriteLine("Attempting to reconnect...");

        try
        {
            await client.ConnectAsync();

            if (client.IsConnected)
            {
                Console.WriteLine("Reconnected to the broker");
                // You can re-subscribe to topics or perform any other necessary actions here
            }
        }
        catch (MqttClientStateException ex)
        {
            Console.WriteLine($"Reconnect attempt failed: {ex.Message}");
        }
    }
```

**Comment by Spike433** [comment]
Hi @pglombardo, thanks for your reply.

I'm using `Host = broker.hivemq.com,` as listed above in the code.

I think you misunderstood my question, I'm not asking why is it happening, my question is what is best way to reconnect?

This is what I had to wrote manually.

```cs

// Run background task that will execute every _sessionExpiryInterval which can be retrieved from broker
protected override Task ExecuteAsync(CancellationToken stoppingToken)
        {
            var timer = new Timer(async (obj) =>
            {
                try
                {
                    await connectAndSubscribeToBroker().ConfigureAwait(false);
                }
                catch (MqttException ex)
                {                    
                    Console.WriteLine($"Error In Connecting To Broker: {ex.Message}");
                }
            }, null, TimeSpan.Zero, TimeSpan.FromSeconds(_sessionExpiryInterval)); // Adjust the interval as needed

            return Task.CompletedTask;
        }
//Polly retry policy
private AsyncRetryPolicy createRetryPolicy()
        {
            return Policy
                .Handle<MqttException>() // Retry when MqttException occurs
                .WaitAndRetryAsync(
                    retryCount: 3, // Maximum number of retries
                    sleepDurationProvider: retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)), // Exponential backoff
                    onRetry: (exception, retryCount, context) =>
                    {
                        Console.WriteLine($"Error In Connecting To Broker. \n Message Type: {exception.Message}\n Retry #{retryCount}");
                    });
        }


//Disconnect than connect to broker again
private async Task connectAndSubscribeToBroker()
        {            
            await createRetryPolicy().ExecuteAsync(async () =>
            {
                Console.WriteLine("\n############ Broker Connection ############");

                await _hiveMQTTClient.DisconnectAsync();

                var connectResult = await _hiveMQTTClient.ConnectAsync().ConfigureAwait(false);
                Console.WriteLine("Connecting to broker ... [{0}]", connectResult.ReasonCode);

                if (connectResult.ReasonCode != HiveMQtt.MQTT5.ReasonCodes.ConnAckReasonCode.Success)
                    throw new MqttException(connectResult.ReasonCode.ToString());
                                
                Console.WriteLine("Connection will expire in [{0}] minutes", connectResult.SessionExpiryInterval / 60);

                await subscribeToTopics();
                _hiveMQTTClient.OnMessageReceived -= Client_OnMessageReceived;
                _hiveMQTTClient.OnMessageReceived += Client_OnMessageReceived;

                Console.WriteLine("############ Broker Connection ############\n");
            });
        }
```

## Bottom line 
Is there a better way to avoid timer and manually disconnect and then connect to broker because all brokers at some point will terminate connection to my client.

**Comment by pglombardo** [comment]
Hrm good point.  We have `OnDisconnectSent` and `OnDisconnectReceived` events but we need a general `AfterDisconnect` that would fire in any disconnect case (even unexpected TCP disconnects).

If we had that, you could then easily add reconnect code to the event handler.  The timer is a fair solution but it's not ideal.

Give me a bit and I'll see if I can add this new event in the next couple days.

**Comment by Spike433** [comment]
Great!

I guess I tried code below but it wasn't working. 
```cs
_hiveMQTTClient.AfterDisconnect += _hiveMQTTClient_AfterDisconnect;
```

I agree with you and thanks!

**Comment by pglombardo** [comment]
Excellent - work is in progress in #89

**Comment by Spike433** [comment]
Hello @pglombardo!

Hope you are doing well.

How long do you estimate it will take to release a new version with fix so I can continue on testing?

**Comment by pglombardo** [comment]
Hi @Spike433 - I was offline most of last week due to a flu.  I'm back and better now though.

If nothing comes up, it should be released this week.  I'm currently testing that it gets triggered correctly with normal and unexpected disconnections.

**Comment by pglombardo** [comment]
Hi @Spike433 - [package 0.4.0 has been released](https://github.com/hivemq/hivemq-mqtt-client-dotnet/releases/tag/v0.4.0) with support for `BeforeDisconnect` and `AfterDisconnect`.  Details and a new example app are linked in the release.

Let me know if you have any issues!

**Comment by Spike433** [comment]
Hello @pglombardo!

I was following your commits and release from yesterday and updated package and code as well.

**Thanks for quick fix and release.**

I will test it out and let you know if there are some other problems, 

Not sure why client started working properly even before this update, like someone update settings on https://www.mqtt-dashboard.com/ that prolongs client connection. We were also sending messages to the client every 5min and maybe that was what kept client alive. 

I will take a look on provided example ❤

Take care!
