### ISSUE TITLE
Timeout exception after publishing on QOS 2 

### ISSUE THREAD

**Issue by angelonardone** [hivemq/hivemq-mqtt-client-dotnet#98]
I connect the the server with a ClientId and "Clean Start" = False.
The idea is to "queue" messages while the cliente is disconnected
Then subscribe to a topic with QOS2 and I can send and receive with no problem up to here.

I disconnect and with the "online client" publish som message to the topic.

When I connect back with the cliente I get the messages that were sent while the client was disconnected.

Put if I try to publish i get a "Timeout exception" (always).
Bellow is part of the client code and the exception is received 5 seconds after we use m_hiveClient.PublishAsync (bellow)

		public void Publish(string topic, string data)
		{
			lock (m_locker)
			{
				if (string.IsNullOrEmpty(topic) || string.IsNullOrEmpty(data))
				{
					throw new Exception("Parámetros no válidos");
				}
				if (!m_hiveClient.IsConnected())
				{
					throw new Exception("Cliente no conectado");
				}

				Log.MsgSnd.Trace($"Client({m_config.clientId}:{m_id}) - Topic({topic}) Data({data})");
				PublishResult result = m_hiveClient.PublishAsync(topic, data, QualityOfService.ExactlyOnceDelivery).Result;
				if (Log.Debug.IsTraceEnabled)
				{
					Log.Debug.Trace($"Client({m_config.clientId}:{m_id}) - PublishResult: {JsonConvert.SerializeObject(result, Formatting.Indented)}");
				}
			}
		}

Here's the error after i Publish a message "hola?" to the topic "angelo"

<MsgSnd>  2023-10-12 09:20:41.2650 (1) GenexusMqtt.Lib.Hive.MqttClient.Publish@232 - Client(client1:569eb2ee-acac-4069-b79a-b15f7ed7eb89) - Topic(angelo) Data(hola?)
<Error>   2023-10-12 09:20:46.2708 (1) GenexusMqtt.Lib.Hive.MqttHandler.Publish@115 - Client(569eb2ee-acac-4069-b79a-b15f7ed7eb89) Topic(angelo) Data(hola?)- Error al publicar el mensaje
System.AggregateException: One or more errors occurred. (The operation has timed out.)
 ---> System.TimeoutException: The operation has timed out.
   at HiveMQtt.Client.HiveMQClient.PublishAsync(MQTT5PublishMessage message)
   at HiveMQtt.Client.HiveMQClient.PublishAsync(String topic, String payload, QualityOfService qos)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at GenexusMqtt.Lib.Hive.MqttClient.Publish(String topic, String data) in C:\Users\Administrator\Documents\mqtt-hive_4\GenexusMqtt.Lib\Hive\MqttClient.cs:line 233
   at GenexusMqtt.Lib.Hive.MqttHandler.Publish(Guid id, String topic, String data) in C:\Users\Administrator\Documents\mqtt-hive_4\GenexusMqtt.Lib\Hive\MqttHandler.cs:line 115
<Error>   2023-10-12 09:20:46.2708 (1) Test.App.MainWindow.PublishClient@187 - Error al publicar el mensaje del cliente 1

**Comment by pglombardo** [comment]
Hi @angelonardone - thanks for reporting and apologies for the issue.  Can you confirm what version of the HiveMQtt package that you are using?

I'll try to reproduce this soon and see what I can find.

**Comment by angelonardone** [comment]
We've found this problem on the version you fixed QOS 2, that was on 0.21.
But I just tested on the latest version (0.43) and it's still there.

**Comment by angelonardone** [comment]
@pglombardo , do you have un estimate on when this is going to be fixed?
Thanks.

**Comment by pglombardo** [comment]
Hi @angelonardone - still preliminary but I'm aiming for next week.  I'll update here once we have progress.

**Comment by pglombardo** [comment]
Hi @angelonardone - how are you doing the client disconnect/reconnect?  Kill the process entirely or interrupting the TCP connection?

**Comment by angelonardone** [comment]
@pglombardo , we are using the  DisconnectAsync. After is disconnected we send messages a Connect Again

**Comment by angelonardone** [comment]
@pglombardo , I've created a video showing the sequence of steps to generate the error, here's the link:

https://entrenarse.s3.amazonaws.com/public/Videos/HiveMQTTproblem.mp4

If you have problems reproducing it I can send you the code

**Comment by pglombardo** [comment]
Hi @angelonardone - I just released [version 0.5.0](https://github.com/hivemq/hivemq-mqtt-client-dotnet/releases/tag/v0.5.0) which fixes this issue also adds a big performance boost.

That package should be on NuGet soon.  Once you get a chance, could you try that package and let me know if this resolves this for you?

**Comment by angelonardone** [comment]
@pglombardo , did something change on the "publish" call? because now I get an error every time I try to "publish",  I get "invalid parameter"

**Comment by pglombardo** [comment]
Nothing changed in the publish API.

There was a change with the `OnPublishQoS2CompleteEvent` - it now returns `List<ControlPacket> packetList`.

Could you post a stack trace? That should point out where the issue is.

Or alternatively enable [trace logging](https://github.com/hivemq/hivemq-mqtt-client-dotnet#logging).

**Comment by pglombardo** [comment]
Hi @angelonardone - have you made any progress on the above?

**Comment by angelonardone** [comment]
@pglombardo , no and it's very strange because we are not using the OnPublishQoS2CompleteEvent at all.
This problem just appeared on the new release.
I'll be working on this during the weekend. I'll let you know.
thanks

**Comment by pglombardo** [comment]
Hrm ok.  We haven't had any other reports of this and the CI/tests all pass...  Let me know what you find.  I'd be happy to help.

**Comment by pglombardo** [comment]
Hi @angelonardone - any update on this?  I'm starting the next wave of fixes/improvements on this client.  Let me know and I'd be happy to investigate.

**Comment by angelonardone** [comment]
I just tried with the version 0.6 and now it's working.
thanks
