### ISSUE TITLE
FR: Add ability to optionally disable broker TLS certificate validation

### ISSUE THREAD

**Issue by pglombardo** [hivemq/hivemq-mqtt-client-dotnet#99]
## 🚀 Feature Request

Some users would like to connect to brokers even if the broker certificate is invalid.

**Comment by AaronTLFranz** [comment]
As of this time, this client library performs certificate validation on TLS connections.  This request would make this feature configurable, enabling or disabling certificate validation for the client.

**Comment by pglombardo** [comment]
Hi @AaronTLFranz - this ability is implemented in #104.  I'll aim to release it this week.

**Comment by pglombardo** [comment]
This new option has been added in [release 0.6.0](https://github.com/hivemq/hivemq-mqtt-client-dotnet/releases/tag/v0.6.0) which is building now and should be on NuGet soon.  Thanks @AaronTLFranz!
